[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5000
  publish = "dist"
  autoLaunch = true

# Fjernet den problematiske redirect for /.netlify/functions/*
# Netlify håndterer automatisk routing til funktioner

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200