[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5000
  publish = "dist"
  autoLaunch = true

[functions]
  node_bundler = "esbuild"

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"
  
[functions.enhance]
  included_files = ["shared/schema.js", "netlify/functions/ai-utils.js"]
  
# Vi kan ikke bruge timeout direkte som en enkelt værdi
# timeout = 30 er ugyldig syntax i Netlify

# Sørg for at API-kald til funktioner bliver korrekt routet
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Også behold direkte adgang til Netlify funktioner
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Alle andre stier går til single-page applikation
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200